[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 
> mmd.emoticon=`tree`


## /start

### Welcome Message<br/>\+ keyboard

#### Keyboard:<br/><br/>\[About, Parsers, Checkers\]

##### About: Creator details \+ info about bot

##### Parsers: Available parsers \+ inline keyboard

###### Inline keyboard: DeWork, Aspecta, Far\.Quest, Phaver, Yup\.io

##### Checkers: Available checkers \+ inline keyboard

###### Inline keyboard: DeBank, Solscan \(in future\)

## Utils \( \#TODO \)<br/>\- Subsriptions<br/>\- Referals<br/>\- Payments options<br/>\- Free trial<br/>\- Update softs \(parsers, checkers\)
> leftSide=`true`

